[package]
name = "blockchain_first"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.9.8"
hex-literal = "0.3.4"
queues = "1.0.2"
chrono = "0.4"
